Traceback (most recent call last):
  File "./QuantumWalk/main.py", line 31, in <module>
    all_results.append(quantum_walk(i,num_qubits,shots,boundary,dist_boundary,coin_type,theta))
  File "/veracruz/projects/c/cquant/QuantumWalk/quantum_walk.py", line 58, in quantum_walk
    decimal_keys = list(map(lambda x: int(x, 2), data_dict.keys()))
  File "/veracruz/projects/c/cquant/QuantumWalk/quantum_walk.py", line 58, in <lambda>
    decimal_keys = list(map(lambda x: int(x, 2), data_dict.keys()))
ValueError: invalid literal for int() with base 2: '110000 00000'
Traceback (most recent call last):
  File "./QuantumWalk/main.py", line 31, in <module>
    all_results.append(quantum_walk(i,num_qubits,shots,boundary,dist_boundary,coin_type,theta))
  File "/veracruz/projects/c/cquant/QuantumWalk/quantum_walk.py", line 58, in quantum_walk
    decimal_keys = list(map(lambda x: int(x, 2), data_dict.keys()))
  File "/veracruz/projects/c/cquant/QuantumWalk/quantum_walk.py", line 58, in <lambda>
    decimal_keys = list(map(lambda x: int(x, 2), data_dict.keys()))
ValueError: invalid literal for int() with base 2: '1100000 000000'
Traceback (most recent call last):
  File "./QuantumWalk/main.py", line 31, in <module>
    all_results.append(quantum_walk(i,num_qubits,shots,boundary,dist_boundary,coin_type,theta))
  File "/veracruz/projects/c/cquant/QuantumWalk/quantum_walk.py", line 58, in quantum_walk
    decimal_keys = list(map(lambda x: int(x, 2), data_dict.keys()))
  File "/veracruz/projects/c/cquant/QuantumWalk/quantum_walk.py", line 58, in <lambda>
    decimal_keys = list(map(lambda x: int(x, 2), data_dict.keys()))
ValueError: invalid literal for int() with base 2: '11000000 0000000'
Traceback (most recent call last):
  File "./QuantumWalk/main.py", line 31, in <module>
    all_results.append(quantum_walk(i,num_qubits,shots,boundary,dist_boundary,coin_type,theta))
  File "/veracruz/projects/c/cquant/QuantumWalk/quantum_walk.py", line 58, in quantum_walk
    decimal_keys = list(map(lambda x: int(x, 2), data_dict.keys()))
  File "/veracruz/projects/c/cquant/QuantumWalk/quantum_walk.py", line 58, in <lambda>
    decimal_keys = list(map(lambda x: int(x, 2), data_dict.keys()))
ValueError: invalid literal for int() with base 2: '110000000 00000000'
slurmstepd: error: acct_gather_profile/influxdb _send_data: curl_easy_perform failed to send data (discarded). Reason: Couldn't connect to server
slurmstepd: error: acct_gather_profile/influxdb _send_data: curl_easy_perform failed to send data (discarded). Reason: Couldn't connect to server
slurmstepd: error: acct_gather_profile/influxdb _send_data: curl_easy_perform failed to send data (discarded). Reason: Couldn't connect to server
slurmstepd: error: acct_gather_profile/influxdb _send_data: curl_easy_perform failed to send data (discarded). Reason: Couldn't connect to server
